### ISSUE TITLE
Current solution for shortening path names doesn't work

### ISSUE THREAD

**Issue by memst** [memst/keats_downloader#5]
If multiple lecture videos have the same name, and are only part numbers are different, the part numbers get cut off and you end up overwriting the file.

**Comment by memst** [comment]
Solution to be implemented:
Add unique index to the start of every filename so that there can't be duplicates.

**Comment by Xiragi** [comment]
May I suggest that the unique index is inline with the ordering of the videos? Currently its sorted alphabetically. That way if watching offline, you know what order to watch it in.

**Comment by dylantjb** [comment]
Although in most cases you would be able to sort by date created / date modified, in the case the videos are uploaded to a cloud service, the videos themselves do not have this metadata. The indexing could also be useful for when there are missing videos.

```py
import os
import sqlite3

MAX_NAME_LENGTH = 40
base_folder = "Library"  # change if necessary

database = sqlite3.connect('main.db')


def add_index(dir_path, index):
    split_dir = dir_path.split('/')
    split_dir[-1] = (str(index) + "_" + split_dir[-1][:len(split_dir[-1])-4])[:MAX_NAME_LENGTH].strip() + ".mp4"
    return '/'.join(split_dir)


for video in database.execute("SELECT * FROM Videos WHERE file_exists IS NOT NULL"):
    dirs = []
    for i in range(4):
        dirs.append((video[i][:MAX_NAME_LENGTH]).strip())

    directory = "{}/{}/{}".format(base_folder, dirs[0], dirs[2])
    path = "{}/{}.mp4".format(directory, dirs[3])

    if os.path.isfile(path):
        videos = [i for i in database.execute("SELECT name FROM Videos WHERE week = ?", [video[2]])]
        os.rename(path, add_index(path, videos.index((video[3],)) + 1))
        #database.execute("UPDATE Videos SET file_exists = TRUE WHERE pageUrl = ?", [video[4]])
    else:
        database.execute("UPDATE Videos SET file_exists = FALSE WHERE pageURL = ?", [video[4]])

database.commit()
```

This modified check_exists.py converts your old videos into the new format (only run once). I advise taking a backup beforehand.

Then for future videos you would use a new list_videos.py
