### ISSUE TITLE
Stuck after point 1 of Basic Usage

### ISSUE THREAD

**Issue by laurenceandrews** [memst/keats_downloader#8]
I have completed all the Requirements steps and step 1 of Basic Usage, however I'm stuck after that point.

I'm not sure which numbered Python files step 2 of Basic Usage refers to, so I tried running Main.py at this point. Chrome loads, lets me log in and opens the link in courses.txt, but then I get the error message below:

`C:\Users\Azeen\Documents\keats_downloader-master>main.py

DevTools listening on ws://127.0.0.1:59279/devtools/browser/6ce4586f-1551-4c01-9005-faa63d4fd270
https://keats.kcl.ac.uk/course/view.php?id=77762
Traceback (most recent call last):
  File "C:\Users\Azeen\Documents\keats_downloader-master\main.py", line 37, in <module>
    scripts.list_videos(courses, database, driver)
  File "C:\Users\Azeen\Documents\keats_downloader-master\downloader\scripts.py", line 34, in list_videos
    videos)
sqlite3.OperationalError: near "ON": syntax error`

Windows 64
Chrome 89.0.4389.114 (Official Build) (64-bit)
ChromeDriver 89.0.4389.23
ffmpeg-N-101799-g0c7d02844c-win64-gpl.zip

Pictures attached of folder structure
![FolderStructure1](https://user-images.githubusercontent.com/50678009/113310184-def75900-92ff-11eb-88a4-1118ecd20772.PNG)
![FolderStructure2](https://user-images.githubusercontent.com/50678009/113310195-e1f24980-92ff-11eb-95dd-9be1c3a10bf7.PNG)`

Pictures attached of folder structure
![FolderStructure1](https://user-images.githubusercontent.com/50678009/113310184-def75900-92ff-11eb-88a4-1118ecd20772.PNG)
![FolderStructure2](https://user-images.githubusercontent.com/50678009/113310195-e1f24980-92ff-11eb-95dd-9be1c3a10bf7.PNG)

**Comment by laurenceandrews** [comment]
Sometimes I get this version of the error instead, having done nothing differently that I can tell:

`DevTools listening on ws://127.0.0.1:59404/devtools/browser/bc4c7c7a-ba9f-4223-ad5b-3b7ab663d158
[10588:1392:0401/155121.684:ERROR:device_event_log_impl.cc(214)] [15:51:21.684] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
https://keats.kcl.ac.uk/course/view.php?id=77762
Traceback (most recent call last):
  File "C:\Users\Azeen\Documents\keats_downloader-master\main.py", line 37, in <module>
    scripts.list_videos(courses, database, driver)
  File "C:\Users\Azeen\Documents\keats_downloader-master\downloader\scripts.py", line 34, in list_videos
    videos)
sqlite3.OperationalError: near "ON": syntax error`

**Comment by POPLOPUK** [comment]
Trying remove the main.db file and then running main.py again.

Additionally what version of python are you running? I ran a clean install just now with version 3.9 and it ran fine.

**Comment by laurenceandrews** [comment]
Python reinstall fixed it thanks, I think it's because I had a duplicate python.exe kicking around. Cheers!
